function mapslashturtlebot5slashvmr0slashvector = load_map(filename, dataLines)
%IMPORTFILE Import data from a text file
%  MAPSLASHTURTLEBOT5SLASHVMR0SLASHVECTOR = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as a table.
%
%  MAPSLASHTURTLEBOT5SLASHVMR0SLASHVECTOR = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  mapslashturtlebot5slashvmr0slashvector = importfile("/home/humberto/projects/magnetometer_pf/synchronized/map__slash_turtlebot5_slash_vmr0_slash_vector.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Apr-2021 12:44:56

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 16);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Magnetometer_timestamp", "mocap_timestamp", "mag_intensity", "mag_vector_x", "mag_vector_y", "mag_vector_z", "pose_x", "pose_y", "pose_z", "roll", "pitch", "yaw", "quat_x", "quat_y", "quat_z", "quat_w"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
mapslashturtlebot5slashvmr0slashvector = readtable(filename, opts);

end